//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPayment
    {
        public int BillPaymentId { get; set; }
        public int FiscalYearId { get; set; }
        public int SubProjectId { get; set; }
        public int BillTypeId { get; set; }
        public int SourceType { get; set; }
        public int PaymentType { get; set; }
        public double PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountName { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual BillType BillType { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual SubProject SubProject { get; set; }
    }
}
