//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultancyFee
    {
        public int CFId { get; set; }
        public Nullable<int> SubProjectId { get; set; }
        public Nullable<int> ConsultantId { get; set; }
        public Nullable<double> ConsultancyFee1 { get; set; }
        public Nullable<double> Vat_Tax { get; set; }
        public Nullable<double> NitAmmountConsultancyFee { get; set; }
        public Nullable<double> OtherConsultancyFee { get; set; }
        public Nullable<double> RestAmount { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual SubProject SubProject { get; set; }
    }
}
