//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultancyActivity
    {
        public int CAId { get; set; }
        public int SubProjectId { get; set; }
        public int ConsultantId { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<int> ConsultantProgressForSupervission { get; set; }
        public Nullable<int> ProgressAccordingToContract { get; set; }
        public Nullable<double> AgreedMoney { get; set; }
        public Nullable<double> PaidMoney { get; set; }
        public Nullable<double> PayableForProgress { get; set; }
        public Nullable<double> RestOfPayableForProgress { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual SubProject SubProject { get; set; }
    }
}
