//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundRelease
    {
        public int FundReleaseId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> FiscalYearID { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public Nullable<double> ReleasedAmount { get; set; }
        public string Remark { get; set; }
    }
}
