//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IDIMDBEntities : DbContext
    {
        public IDIMDBEntities()
            : base("name=IDIMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SetupLocation> SetupLocations { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<BillPayment> BillPayments { get; set; }
        public virtual DbSet<BillType> BillTypes { get; set; }
        public virtual DbSet<ConstructionFirm> ConstructionFirms { get; set; }
        public virtual DbSet<ProjectExtend> ProjectExtends { get; set; }
        public virtual DbSet<ProjectProblem> ProjectProblems { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<Quarter> Quarters { get; set; }
        public virtual DbSet<ReceiptPayment> ReceiptPayments { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserApplication> UserApplications { get; set; }
        public virtual DbSet<UserDevice> UserDevices { get; set; }
        public virtual DbSet<UserLoginDevice> UserLoginDevices { get; set; }
        public virtual DbSet<UserPriviledge> UserPriviledges { get; set; }
        public virtual DbSet<ViewProjectInformationRpt> ViewProjectInformationRpts { get; set; }
        public virtual DbSet<ViewProjectPaymentReceiptRpt> ViewProjectPaymentReceiptRpts { get; set; }
        public virtual DbSet<ViewProjectProblemRpt> ViewProjectProblemRpts { get; set; }
        public virtual DbSet<ViewProjectSubProjectDetailsRpt> ViewProjectSubProjectDetailsRpts { get; set; }
        public virtual DbSet<ViewProjectWiseSubProjectRpt> ViewProjectWiseSubProjectRpts { get; set; }
        public virtual DbSet<FiscalYear> FiscalYears { get; set; }
        public virtual DbSet<PicMeeting> PicMeetings { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<SetupUnit> SetupUnits { get; set; }
        public virtual DbSet<SubProject> SubProjects { get; set; }
        public virtual DbSet<GeneralInformation> GeneralInformations { get; set; }
        public virtual DbSet<ConsultancyActivity> ConsultancyActivities { get; set; }
        public virtual DbSet<ConsultancyFee> ConsultancyFees { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<SubProjectDetail> SubProjectDetails { get; set; }
        public virtual DbSet<ViewProjectList> ViewProjectLists { get; set; }
        public virtual DbSet<ViewProjectBillPayment> ViewProjectBillPayments { get; set; }
        public virtual DbSet<FundRelease> FundReleases { get; set; }
        public virtual DbSet<ViewExtended> ViewExtendeds { get; set; }
        public virtual DbSet<ViewProjectProblem> ViewProjectProblems { get; set; }
        public virtual DbSet<SecurityDeposit> SecurityDeposits { get; set; }
    
        public virtual ObjectResult<sp_ProjectStatus_Result1> sp_ProjectStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProjectStatus_Result1>("sp_ProjectStatus");
        }
    }
}
