//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicMeeting
    {
        public int PicMeetingId { get; set; }
        public string PicMeetingTitle { get; set; }
        public System.DateTime PicMeetingDate { get; set; }
        public int ProjectId { get; set; }
        public string PicMeetingDescription { get; set; }
        public string PscMeetingDescription { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
