//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatu
    {
        public int ProjectStatusId { get; set; }
        public int SubProjectId { get; set; }
        public string Progress { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual SubProject SubProject { get; set; }
    }
}
