//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectExtend
    {
        public int ProjectExtendId { get; set; }
        public int SubProjectId { get; set; }
        public int NoOfDays { get; set; }
        public Nullable<System.DateTime> ExtendDate { get; set; }
        public Nullable<System.DateTime> NewHandOverDate { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual SubProject SubProject { get; set; }
    }
}
