//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.PicMeetings = new HashSet<PicMeeting>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
            this.SubProjects = new HashSet<SubProject>();
        }
    
        public int ProjectId { get; set; }
        public int AuthorizeUnitId { get; set; }
        public int FiscalYearId { get; set; }
        public int DevelopmentTypeId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public string ProjectDirector { get; set; }
        public double BudgetCapital { get; set; }
        public double BudgetRevenue { get; set; }
        public string Description { get; set; }
        public string PicMeetingNo { get; set; }
        public string PicMeetingDescriptioin { get; set; }
        public string PscMeetingDescription { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicMeeting> PicMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubProject> SubProjects { get; set; }
    }
}
