//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPayment
    {
        public int ReceiptPaymentId { get; set; }
        public int ProjectId { get; set; }
        public int FiscalYearId { get; set; }
        public int QuarterId { get; set; }
        public int DocumentType { get; set; }
        public int SourceType { get; set; }
        public double ReceiptAmount { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual Quarter Quarter { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
        public virtual Project Project { get; set; }
    }
}
