//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityDeposit
    {
        public int SecurityDepositId { get; set; }
        public Nullable<int> SubProjectId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Letterdate { get; set; }
        public string Letterno { get; set; }
        public string Remark { get; set; }
    
        public virtual SubProject SubProject { get; set; }
    }
}
