//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProjectDetail
    {
        public int SubProjectDetailsId { get; set; }
        public Nullable<int> SubProjectId { get; set; }
        public Nullable<bool> hasCompleted { get; set; }
        public string BGOrPayOrder { get; set; }
        public Nullable<bool> BGConfirmed { get; set; }
        public Nullable<bool> ContractComplete { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<bool> DesignSent { get; set; }
        public Nullable<double> Installment1 { get; set; }
        public Nullable<double> Installment2 { get; set; }
        public Nullable<double> Installment4 { get; set; }
        public Nullable<double> Installment5 { get; set; }
        public Nullable<double> TotalAmmount { get; set; }
        public Nullable<double> BGBMiscellaneousDeposit { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<bool> IsFinalBillPaid { get; set; }
        public Nullable<bool> TenPercentGuarantee { get; set; }
        public Nullable<bool> FivePercentSecurityMoney { get; set; }
        public Nullable<double> TenPercentPaidFarm { get; set; }
        public Nullable<double> TenPercentPaidSimantoFund { get; set; }
        public Nullable<double> ContractorPayable { get; set; }
        public string Remark { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual SubProject SubProject { get; set; }
    }
}
