//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginDevice
    {
        public int UserDeviceId { get; set; }
        public int UserId { get; set; }
        public int DeviceId { get; set; }
        public string Session { get; set; }
        public string ValidationCode { get; set; }
        public System.DateTime LoggedIn { get; set; }
        public Nullable<System.DateTime> Loggedout { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual User User { get; set; }
    }
}
