//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public int UserApplicationId { get; set; }
        public int UserId { get; set; }
        public int ApplicationId { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public int UpdateNo { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
