//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectBillPayment
    {
        public int BillPaymentId { get; set; }
        public string ProjectName { get; set; }
        public string SubProjectTitle { get; set; }
        public string FiscalYearDescription { get; set; }
        public string UnitName { get; set; }
        public string ConstructionFirmName { get; set; }
        public double AgreementCost { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public string Remark { get; set; }
        public int ProjectId { get; set; }
        public int SubProjectId { get; set; }
        public string ProjectStatus { get; set; }
        public string BudgetType { get; set; }
        public int FiscalYearId { get; set; }
        public double BudgetCapital { get; set; }
        public double BudgetRevenue { get; set; }
        public int ConstructionFirmId { get; set; }
        public int BillTypeId { get; set; }
        public string SourceType { get; set; }
        public string PaymentType { get; set; }
        public double PaymentAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BillTypeName { get; set; }
    }
}
