//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectPaymentReceiptRpt
    {
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string UnitName { get; set; }
        public string FiscalYearDescription { get; set; }
        public string QuarterName { get; set; }
        public string DocumentType { get; set; }
        public string SourceType { get; set; }
        public double ReceiptAmount { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string Remark { get; set; }
        public int ProjectId { get; set; }
        public int AuthorizeUnitId { get; set; }
        public int FiscalYearId { get; set; }
        public int QuarterId { get; set; }
    }
}
