//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectProblemRpt
    {
        public string UnitName { get; set; }
        public string ProjectName { get; set; }
        public string SubProjectTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> SolveDate { get; set; }
        public bool Status { get; set; }
        public int SubProjectId { get; set; }
        public int UnitId { get; set; }
        public int ProjectId { get; set; }
        public int ProjectProblemId { get; set; }
    }
}
