//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectWiseSubProjectRpt
    {
        public int ProjectId { get; set; }
        public string FiscalYearDescription { get; set; }
        public string UnitName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string SubProjectTitle { get; set; }
        public string Description { get; set; }
        public string ConstructionFirmName { get; set; }
        public double AgreementCost { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public string Remark { get; set; }
        public int ConstructionFirmId { get; set; }
        public string SubProjectUnit { get; set; }
    }
}
