//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectInformationRpt
    {
        public int ProjectId { get; set; }
        public string FiscalYearDescription { get; set; }
        public string UnitName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public string ProjectDirector { get; set; }
        public double BudgetCapital { get; set; }
        public double BudgetRevenue { get; set; }
        public string Description { get; set; }
        public string PicMeetingNo { get; set; }
        public string Remark { get; set; }
        public int AuthorizeUnitId { get; set; }
        public int FiscalYearId { get; set; }
    }
}
