//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDIMWorkBranchProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProjectSubProjectDetailsRpt
    {
        public int ProjectId { get; set; }
        public string FiscalYearDescription { get; set; }
        public int AuthorizeUnitId { get; set; }
        public string ProjectName { get; set; }
        public string SubProjectTitle { get; set; }
        public string Description { get; set; }
        public string UnitName { get; set; }
        public string ProjectUnit { get; set; }
        public int FiscalYearId { get; set; }
        public int UnitId { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SolveDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<System.DateTime> ExtendDate { get; set; }
        public Nullable<System.DateTime> NewHandOverDate { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public string ConstructionFirmName { get; set; }
        public double AgreementCost { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int Subprojectstatus { get; set; }
        public Nullable<System.DateTime> HandOverDate { get; set; }
        public string Subprojectremark { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public string ProjectDirector { get; set; }
        public double BudgetCapital { get; set; }
        public double BudgetRevenue { get; set; }
        public string projectdescription { get; set; }
        public string PicMeetingNo { get; set; }
        public string Projectremark { get; set; }
        public string SourceType { get; set; }
        public string PaymentType { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountName { get; set; }
        public int SubProjectId { get; set; }
        public string BillTypeName { get; set; }
        public Nullable<int> BillTypeId { get; set; }
        public int ProjectStatusId { get; set; }
        public string Progress { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string StatusDescription { get; set; }
        public string StatusRemark { get; set; }
    }
}
